<?php return unserialize('O:8:"stdClass":6:{s:3:"cid";s:36:"http://beta.lipidboard.org/user:html";s:4:"data";O:41:"Drupal\\Core\\Routing\\LocalRedirectResponse":9:{s:12:"' . "\0" . '*' . "\0" . 'targetUrl";s:37:"http://beta.lipidboard.org/user/login";s:7:"headers";O:50:"Symfony\\Component\\HttpFoundation\\ResponseHeaderBag":5:{s:23:"' . "\0" . '*' . "\0" . 'computedCacheControl";a:3:{s:15:"must-revalidate";b:1;s:8:"no-cache";b:1;s:7:"private";b:1;}s:10:"' . "\0" . '*' . "\0" . 'cookies";a:0:{}s:14:"' . "\0" . '*' . "\0" . 'headerNames";a:9:{s:13:"cache-control";s:13:"Cache-Control";s:8:"location";s:8:"Location";s:15:"x-ua-compatible";s:15:"X-UA-Compatible";s:16:"content-language";s:16:"Content-language";s:22:"x-content-type-options";s:22:"X-Content-Type-Options";s:15:"x-frame-options";s:15:"X-Frame-Options";s:7:"expires";s:7:"Expires";s:4:"vary";s:4:"Vary";s:11:"x-generator";s:11:"X-Generator";}s:10:"' . "\0" . '*' . "\0" . 'headers";a:9:{s:13:"cache-control";a:1:{i:0;s:34:"must-revalidate, no-cache, private";}s:8:"location";a:1:{i:0;s:37:"http://beta.lipidboard.org/user/login";}s:15:"x-ua-compatible";a:1:{i:0;s:7:"IE=edge";}s:16:"content-language";a:1:{i:0;s:2:"en";}s:22:"x-content-type-options";a:1:{i:0;s:7:"nosniff";}s:15:"x-frame-options";a:1:{i:0;s:10:"SAMEORIGIN";}s:7:"expires";a:1:{i:0;s:29:"Sun, 19 Nov 1978 05:00:00 GMT";}s:4:"vary";a:0:{}s:11:"x-generator";a:1:{i:0;s:33:"Drupal 8 (https://www.drupal.org)";}}s:15:"' . "\0" . '*' . "\0" . 'cacheControl";a:3:{s:15:"must-revalidate";b:1;s:8:"no-cache";b:1;s:7:"private";b:1;}}s:10:"' . "\0" . '*' . "\0" . 'content";s:392:"<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://beta.lipidboard.org/user/login" />

        <title>Redirecting to http://beta.lipidboard.org/user/login</title>
    </head>
    <body>
        Redirecting to <a href="http://beta.lipidboard.org/user/login">http://beta.lipidboard.org/user/login</a>.
    </body>
</html>";s:10:"' . "\0" . '*' . "\0" . 'version";s:3:"1.0";s:13:"' . "\0" . '*' . "\0" . 'statusCode";i:302;s:13:"' . "\0" . '*' . "\0" . 'statusText";s:5:"Found";s:10:"' . "\0" . '*' . "\0" . 'charset";N;s:23:"' . "\0" . '*' . "\0" . 'cacheabilityMetadata";O:35:"Drupal\\Core\\Cache\\CacheableMetadata":3:{s:16:"' . "\0" . '*' . "\0" . 'cacheContexts";a:0:{}s:12:"' . "\0" . '*' . "\0" . 'cacheTags";a:0:{}s:14:"' . "\0" . '*' . "\0" . 'cacheMaxAge";i:0;}s:17:"' . "\0" . '*' . "\0" . 'requestContext";O:34:"Drupal\\Core\\Routing\\RequestContext":11:{s:18:"' . "\0" . '*' . "\0" . 'completeBaseUrl";s:26:"http://beta.lipidboard.org";s:49:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'baseUrl";s:0:"";s:50:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'pathInfo";s:5:"/user";s:48:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'method";s:3:"GET";s:46:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'host";s:19:"beta.lipidboard.org";s:48:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'scheme";s:4:"http";s:50:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'httpPort";i:80;s:51:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'httpsPort";i:443;s:53:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'queryString";s:0:"";s:52:"' . "\0" . 'Symfony\\Component\\Routing\\RequestContext' . "\0" . 'parameters";a:0:{}s:10:"_serviceId";s:22:"router.request_context";}}s:7:"created";d:1505405767.984;s:6:"expire";i:-1;s:4:"tags";a:0:{}s:8:"checksum";i:0;}');